# maps country names in Russian and English into two symbol codes

countryToCode = {
    'AB' : 	'AB',
    'AU' : 	'AU',
    'AT' : 	'AT',
    'AZ' : 	'AZ',
    'AL' : 	'AL',
    'DZ' : 	'DZ',
    'AI' : 	'AI',
    'AO' : 	'AO',
    'AD' : 	'AD',
    'AQ' : 	'AQ',
    'AG' : 	'AG',
    'AR' : 	'AR',
    'AM' : 	'AM',
    'AW' : 	'AW',
    'AF' : 	'AF',
    'BS' : 	'BS',
    'BD' : 	'BD',
    'BB' : 	'BB',
    'BH' : 	'BH',
    'BY' : 	'BY',
    'BZ' : 	'BZ',
    'BE' : 	'BE',
    'BJ' : 	'BJ',
    'BM' : 	'BM',
    'BG' : 	'BG',
    'BO' : 	'BO',
    'BQ' : 	'BQ',
    'BA' : 	'BA',
    'BW' : 	'BW',
    'BR' : 	'BR',
    'VG' : 	'VG',
    'IO' : 	'IO',
    'BN' : 	'BN',
    'BV' : 	'BV',
    'BF' : 	'BF',
    'BI' : 	'BI',
    'BT' : 	'BT',
    'VU' : 	'VU',
    'VA' : 	'VA',
    'GB' : 	'GB',
    'HU' : 	'HU',
    'VE' : 	'VE',
    'VI' : 	'VI',
    'AS' : 	'AS',
    'VN' : 	'VN',
    'GA' : 	'GA',
    'HT' : 	'HT',
    'GY' : 	'GY',
    'GM' : 	'GM',
    'GH' : 	'GH',
    'GP' : 	'GP',
    'GT' : 	'GT',
    'GN' : 	'GN',
    'GW' : 	'GW',
    'DE' : 	'DE',
    'GG' : 	'GG',
    'GI' : 	'GI',
    'HN' : 	'HN',
    'HK' : 	'HK',
    'GD' : 	'GD',
    'GL' : 	'GL',
    'GR' : 	'GR',
    'GE' : 	'GE',
    'GU' : 	'GU',
    'DK' : 	'DK',
    'CD' : 	'CD',
    'JE' : 	'JE',
    'DJ' : 	'DJ',
    'DM' : 	'DM',
    'DO' : 	'DO',
    'EG' : 	'EG',
    'ZM' : 	'ZM',
    'EH' : 	'EH',
    'ZW' : 	'ZW',
    'IL' : 	'IL',
    'IN' : 	'IN',
    'ID' : 	'ID',
    'JO' : 	'JO',
    'IQ' : 	'IQ',
    'IR' : 	'IR',
    'IE' : 	'IE',
    'IS' : 	'IS',
    'ES' : 	'ES',
    'IT' : 	'IT',
    'YE' : 	'YE',
    'CV' : 	'CV',
    'KZ' : 	'KZ',
    'KY' : 	'KY',
    'KH' : 	'KH',
    'CM' : 	'CM',
    'CA' : 	'CA',
    'QA' : 	'QA',
    'KE' : 	'KE',
    'CY' : 	'CY',
    'KG' : 	'KG',
    'KI' : 	'KI',
    'CN' : 	'CN',
    'KP' : 	'KP',
    'CC' : 	'CC',
    'CO' : 	'CO',
    'KM' : 	'KM',
    'KR' : 	'KR',
    'XK' : 	'XK',
    'CR' : 	'CR',
    'CI' : 	'CI',
    'CU' : 	'CU',
    'KW' : 	'KW',
    'CK' : 	'CK',
    'CW' : 	'CW',
    'LA' : 	'LA',
    'LV' : 	'LV',
    'LS' : 	'LS',
    'LR' : 	'LR',
    'LB' : 	'LB',
    'LY' : 	'LY',
    'LT' : 	'LT',
    'LI' : 	'LI',
    'LU' : 	'LU',
    'MU' : 	'MU',
    'MR' : 	'MR',
    'MG' : 	'MG',
    'YT' : 	'YT',
    'MO' : 	'MO',
    'MK' : 	'MK',
    'MW' : 	'MW',
    'MY' : 	'MY',
    'ML' : 	'ML',
    'UM' : 	'UM',
    'MV' : 	'MV',
    'MT' : 	'MT',
    'MA' : 	'MA',
    'MQ' : 	'MQ',
    'MH' : 	'MH',
    'MX' : 	'MX',
    'FM' : 	'FM',
    'MZ' : 	'MZ',
    'MD' : 	'MD',
    'MC' : 	'MC',
    'MN' : 	'MN',
    'MS' : 	'MS',
    'MM' : 	'MM',
    'IM' : 	'IM',
    'NA' : 	'NA',
    'NR' : 	'NR',
    'NP' : 	'NP',
    'NE' : 	'NE',
    'NG' : 	'NG',
    'NL' : 	'NL',
    'NI' : 	'NI',
    'NU' : 	'NU',
    'NZ' : 	'NZ',
    'NC' : 	'NC',
    'NO' : 	'NO',
    'NF' : 	'NF',
    'AE' : 	'AE',
    'OM' : 	'OM',
    'PK' : 	'PK',
    'PW' : 	'PW',
    'PS' : 	'PS',
    'PA' : 	'PA',
    'PG' : 	'PG',
    'PY' : 	'PY',
    'PE' : 	'PE',
    'PN' : 	'PN',
    'PL' : 	'PL',
    'PT' : 	'PT',
    'PR' : 	'PR',
    'CG' : 	'CG',
    'RE' : 	'RE',
    'CX' : 	'CX',
    'RU' : 	'RU',
    'RW' : 	'RW',
    'RO' : 	'RO',
    'SV' : 	'SV',
    'WS' : 	'WS',
    'SM' : 	'SM',
    'ST' : 	'ST',
    'SA' : 	'SA',
    'SZ' : 	'SZ',
    'SH' : 	'SH',
    'MP' : 	'MP',
    'SC' : 	'SC',
    'BL' : 	'BL',
    'SN' : 	'SN',
    'MF' : 	'MF',
    'PM' : 	'PM',
    'VC' : 	'VC',
    'KN' : 	'KN',
    'LC' : 	'LC',
    'SX' : 	'SX',
    'RS' : 	'RS',
    'SG' : 	'SG',
    'SY' : 	'SY',
    'SK' : 	'SK',
    'SI' : 	'SI',
    'US' : 	'US',
    'SB' : 	'SB',
    'SO' : 	'SO',
    'SD' : 	'SD',
    'SR' : 	'SR',
    'SL' : 	'SL',
    'TJ' : 	'TJ',
    'TH' : 	'TH',
    'TW' : 	'TW',
    'TZ' : 	'TZ',
    'TC' : 	'TC',
    'TL' : 	'TL',
    'TG' : 	'TG',
    'TK' : 	'TK',
    'TO' : 	'TO',
    'TT' : 	'TT',
    'TV' : 	'TV',
    'TN' : 	'TN',
    'TM' : 	'TM',
    'TR' : 	'TR',
    'UG' : 	'UG',
    'UZ' : 	'UZ',
    'UA' : 	'UA',
    'WF' : 	'WF',
    'UY' : 	'UY',
    'FO' : 	'FO',
    'FJ' : 	'FJ',
    'PH' : 	'PH',
    'FI' : 	'FI',
    'FK' : 	'FK',
    'FR' : 	'FR',
    'GF' : 	'GF',
    'PF' : 	'PF',
    'TF' : 	'TF',
    'HM' : 	'HM',
    'HR' : 	'HR',
    'CF' : 	'CF',
    'TD' : 	'TD',
    'ME' : 	'ME',
    'CZ' : 	'CZ',
    'CL' : 	'CL',
    'CH' : 	'CH',
    'SE' : 	'SE',
    'SJ' : 	'SJ',
    'LK' : 	'LK',
    'EC' : 	'EC',
    'GQ' : 	'GQ',
    'AX' : 	'AX',
    'ER' : 	'ER',
    'EE' : 	'EE',
    'ET' : 	'ET',
    'GS' : 	'GS',
    'OS' : 	'OS',
    'ZA' : 	'ZA',
    'SS' : 	'SS',
    'JM' : 	'JM',
    'JP' : 	'JP',

    'ABH' : 	'AB',
    'AUS' : 	'AU',
    'AUT' : 	'AT',
    'AZE' : 	'AZ',
    'ALB' : 	'AL',
    'DZA' : 	'DZ',
    'AIA' : 	'AI',
    'AGO' : 	'AO',
    'AND' : 	'AD',
    'ATA' : 	'AQ',
    'ATG' : 	'AG',
    'ARG' : 	'AR',
    'ARM' : 	'AM',
    'ABW' : 	'AW',
    'AFG' : 	'AF',
    'BHS' : 	'BS',
    'BGD' : 	'BD',
    'BRB' : 	'BB',
    'BHR' : 	'BH',
    'BLR' : 	'BY',
    'BLZ' : 	'BZ',
    'BEL' : 	'BE',
    'BEN' : 	'BJ',
    'BMU' : 	'BM',
    'BGR' : 	'BG',
    'BUL' : 	'BG',
    'BOL' : 	'BO',
    'BES' : 	'BQ',
    'BIH' : 	'BA',
    'BWA' : 	'BW',
    'BRA' : 	'BR',
    'VGB' : 	'VG',
    'IOT' : 	'IO',
    'BRN' : 	'BN',
    'BVT' : 	'BV',
    'BFA' : 	'BF',
    'BDI' : 	'BI',
    'BTN' : 	'BT',
    'VUT' : 	'VU',
    'VAT' : 	'VA',
    'GBR' : 	'GB',
    'HUN' : 	'HU',
    'VEN' : 	'VE',
    'VIR' : 	'VI',
    'ASM' : 	'AS',
    'VNM' : 	'VN',
    'GAB' : 	'GA',
    'HTI' : 	'HT',
    'GUY' : 	'GY',
    'GMB' : 	'GM',
    'GHA' : 	'GH',
    'GLP' : 	'GP',
    'GTM' : 	'GT',
    'GIN' : 	'GN',
    'GNB' : 	'GW',
    'DEU' : 	'DE',
    'GGY' : 	'GG',
    'GIB' : 	'GI',
    'HND' : 	'HN',
    'HKG' : 	'HK',
    'GRD' : 	'GD',
    'GRL' : 	'GL',
    'GRC' : 	'GR',
    'GRE' : 	'GR',
    'GEO' : 	'GE',
    'GUM' : 	'GU',
    'DNK' : 	'DK',
    'COD' : 	'CD',
    'JEY' : 	'JE',
    'DJI' : 	'DJ',
    'DMA' : 	'DM',
    'DOM' : 	'DO',
    'EGY' : 	'EG',
    'ZMB' : 	'ZM',
    'ESH' : 	'EH',
    'ZWE' : 	'ZW',
    'ISR' : 	'IL',
    'IND' : 	'IN',
    'IDN' : 	'ID',
    'INS' : 	'ID',
    'JOR' : 	'JO',
    'IRQ' : 	'IQ',
    'IRN' : 	'IR',
    'IRL' : 	'IE',
    'ISL' : 	'IS',
    'ESP' : 	'ES',
    'ITA' : 	'IT',
    'YEM' : 	'YE',
    'CPV' : 	'CV',
    'KAZ' : 	'KZ',
    'CYM' : 	'KY',
    'KHM' : 	'KH',
    'CMR' : 	'CM',
    'CAN' : 	'CA',
    'QAT' : 	'QA',
    'KTA' : 	'QA',
    'KEN' : 	'KE',
    'CYP' : 	'CY',
    'KGZ' : 	'KG',
    'KIR' : 	'KI',
    'CHN' : 	'CN',
    'PRK' : 	'KP',
    'CCK' : 	'CC',
    'COL' : 	'CO',
    'KOM' : 	'KM',
    'KOR' : 	'KR',
    'KOS' : 	'XK',
    'CRI' : 	'CR',
    'CIV' : 	'CI',
    'CUB' : 	'CU',
    'KWT' : 	'KW',
    'COK' : 	'CK',
    'CUW' : 	'CW',
    'LAO' : 	'LA',
    'LVA' : 	'LV',
    'LSO' : 	'LS',
    'LBR' : 	'LR',
    'LBN' : 	'LB',
    'LBY' : 	'LY',
    'LTU' : 	'LT',
    'LIE' : 	'LI',
    'LUX' : 	'LU',
    'MUS' : 	'MU',
    'MRT' : 	'MR',
    'MDG' : 	'MG',
    'MYT' : 	'YT',
    'MAC' : 	'MO',
    'MKD' : 	'MK',
    'MWI' : 	'MW',
    'MYS' : 	'MY',
    'MLI' : 	'ML',
    'UMI' : 	'UM',
    'MDV' : 	'MV',
    'MLT' : 	'MT',
    'MAR' : 	'MA',
    'MTQ' : 	'MQ',
    'MHL' : 	'MH',
    'MEX' : 	'MX',
    'FSM' : 	'FM',
    'MOZ' : 	'MZ',
    'MDA' : 	'MD',
    'MCO' : 	'MC',
    'MNG' : 	'MN',
    'MSR' : 	'MS',
    'MMR' : 	'MM',
    'IMN' : 	'IM',
    'NAM' : 	'NA',
    'NRU' : 	'NR',
    'NPL' : 	'NP',
    'NER' : 	'NE',
    'NGA' : 	'NG',
    'NLD' : 	'NL',
    'NIC' : 	'NI',
    'NIU' : 	'NU',
    'NZL' : 	'NZ',
    'NCL' : 	'NC',
    'NOR' : 	'NO',
    'NFK' : 	'NF',
    'ARE' : 	'AE',
    'OMN' : 	'OM',
    'PAK' : 	'PK',
    'PLW' : 	'PW',
    'PSE' : 	'PS',
    'PAN' : 	'PA',
    'PNG' : 	'PG',
    'PRY' : 	'PY',
    'PER' : 	'PE',
    'PCN' : 	'PN',
    'POL' : 	'PL',
    'PRT' : 	'PT',
    'PRI' : 	'PR',
    'COG' : 	'CG',
    'REU' : 	'RE',
    'CXR' : 	'CX',
    'RUS' : 	'RU',
    'RWA' : 	'RW',
    'ROM' : 	'RO',
    'SLV' : 	'SV',
    'WSM' : 	'WS',
    'SMR' : 	'SM',
    'STP' : 	'ST',
    'SAU' : 	'SA',
    'SWZ' : 	'SZ',
    'SHN' : 	'SH',
    'MNP' : 	'MP',
    'SYC' : 	'SC',
    'BLM' : 	'BL',
    'SEN' : 	'SN',
    'MAF' : 	'MF',
    'SPM' : 	'PM',
    'VCT' : 	'VC',
    'KNA' : 	'KN',
    'LCA' : 	'LC',
    'SXM' : 	'SX',
    'SRB' : 	'RS',
    'SGP' : 	'SG',
    'SYR' : 	'SY',
    'SVK' : 	'SK',
    'SVN' : 	'SI',
    'USA' : 	'US',
    'SLB' : 	'SB',
    'SOM' : 	'SO',
    'SDN' : 	'SD',
    'SUR' : 	'SR',
    'SLE' : 	'SL',
    'TJK' : 	'TJ',
    'THA' : 	'TH',
    'TWN' : 	'TW',
    'TZA' : 	'TZ',
    'TCA' : 	'TC',
    'TLS' : 	'TL',
    'TGO' : 	'TG',
    'TKL' : 	'TK',
    'TON' : 	'TO',
    'TTO' : 	'TT',
    'TUV' : 	'TV',
    'TUN' : 	'TN',
    'TKM' : 	'TM',
    'TUR' : 	'TR',
    'UGA' : 	'UG',
    'UZB' : 	'UZ',
    'UKR' : 	'UA',
    'WLF' : 	'WF',
    'URY' : 	'UY',
    'FRO' : 	'FO',
    'FJI' : 	'FJ',
    'PHL' : 	'PH',
    'FIN' : 	'FI',
    'FKL' : 	'FK',
    'FRA' : 	'FR',
    'GUF' : 	'GF',
    'PYF' : 	'PF',
    'ATF' : 	'TF',
    'HMD' : 	'HM',
    'HRV' : 	'HR',
    'CAF' : 	'CF',
    'TCD' : 	'TD',
    'MNE' : 	'ME',
    'CZE' : 	'CZ',
    'CHL' : 	'CL',
    'CHE' : 	'CH',
    'SWE' : 	'SE',
    'SJM' : 	'SJ',
    'LKA' : 	'LK',
    'ECU' : 	'EC',
    'GNQ' : 	'GQ',
    'ALA' : 	'AX',
    'ERI' : 	'ER',
    'EST' : 	'EE',
    'ETH' : 	'ET',
    'SGS' : 	'GS',
    'OST' : 	'OS',
    'ZAF' : 	'ZA',
    'SSD' : 	'SS',
    'JAM' : 	'JM',
    'JPN' : 	'JP',

    'UNK' :     'AF',
    'PHI' :     'PH',
    'SAF' :     'ZA',
    'DEN' :     'DK',
    'KSV' :     'XK',
    'POR' :     'PT',
    'GER' :     'DE',
    'HEL' :     'GR',
    'MAS' :     'MY',
    'SUI' :     'CH',
    'ALG' :     'DZ',
    'CHI' :     'CL',
    'PAR' :     'PY',
    'UAE' :     'AE',
    'ROU' :     'RO',

    'Abkhazia' : 	'AB',
    'Australia' : 	'AU',
    'Austria' : 	'AT',
    'Azerbaijan' : 	'AZ',
    'Albania' : 	'AL',
    'Algeria' : 	'DZ',
    'Anguilla' : 	'AI',
    'Angola' : 	'AO',
    'Andorra' : 	'AD',
    'Antarctica' : 	'AQ',
    'Antigua and Barbuda' : 	'AG',
    'Argentina' : 	'AR',
    'Armenia' : 	'AM',
    'Aruba' : 	'AW',
    'Afghanistan' : 	'AF',
    'Bahamas' : 	'BS',
    'Bangladesh' : 	'BD',
    'Barbados' : 	'BB',
    'Bahrain' : 	'BH',
    'Belarus' : 	'BY',
    'Belize' : 	'BZ',
    'Belgium' : 	'BE',
    'Benin' : 	'BJ',
    'Bermuda' : 	'BM',
    'Bulgaria' : 	'BG',
    'Republic of Bulgaria' : 	'BG',
    'Bolivia' : 	'BO',
    'Bonaire, Sint Eustatius and Saba' : 	'BQ',
    'Bosnia and herzegovina' : 	'BA',
    'Bosnia and Herzegovina' : 	'BA',
    'Bosnia and Hercegovina' : 	'BA',
    'Bosnia And Herzegovina' : 	'BA',
    'Bih' : 	'BA',
    'Botswana' : 	'BW',
    'Brazil' : 	'BR',
    'Virgin islands (british)' : 	'VG',
    'British Indian ocean territory' : 	'IO',
    'Brunei' : 	'BN',
    'Bouvet island' : 	'BV',
    'Burkina Faso' : 	'BF',
    'Burundi' : 	'BI',
    'Bhutan' : 	'BT',
    'Vanuatu' : 	'VU',
    'Vatican' : 	'VA',
    'United Kingdom' : 	'GB',
    'Great Britain' : 	'GB',
    'Hungary' : 	'HU',
    'Venezuela' : 	'VE',
    'Virgin islands (US)' : 	'VI',
    'American Samoa' : 	'AS',
    'Viet nam' : 	'VN',
    'Viet Nam' : 	'VN',
    'Vietnam' : 	'VN',
    'Gabon' : 	'GA',
    'Haiti' : 	'HT',
    'Guyana' : 	'GY',
    'Gambia' : 	'GM',
    'Ghana' : 	'GH',
    'Guadeloupe' : 	'GP',
    'Guatemala' : 	'GT',
    'Guinea' : 	'GN',
    'Guinea-Bissau' : 	'GW',
    'Germany' : 	'DE',
    'Guernsey' : 	'GG',
    'Gibraltar' : 	'GI',
    'Honduras' : 	'HN',
    'Hong kong' : 	'HK',
    'Hong Kong' : 	'HK',
    'Grenada' : 	'GD',
    'Greenland' : 	'GL',
    'Greece' : 	'GR',
    'Georgia' : 	'GE',
    'Guam' : 	'GU',
    'Denmark' : 	'DK',
    'Congo (DR)' : 	'CD',
    'Jersey' : 	'JE',
    'Djibouti' : 	'DJ',
    'Dominica' : 	'DM',
    'Dominican Republic' : 	'DO',
    'Egypt' : 	'EG',
    'Zambia' : 	'ZM',
    'Western Sahara' : 	'EH',
    'Zimbabwe' : 	'ZW',
    'Israel' : 	'IL',
    'India' : 	'IN',
    'Indonesia' : 	'ID',
    'Republic of Indonesia' : 	'ID',
    'Jordan' : 	'JO',
    'Iraq' : 	'IQ',
    'Iran' : 	'IR',
    'Islamic Republic of Iran' :    'IR',
    'Ireland' : 	'IE',
    'Iceland' : 	'IS',
    'Spain' : 	'ES',
    'Italy' : 	'IT',
    'Yemen' : 	'YE',
    'Cabo verde' : 	'CV',
    'Kazakhstan' : 	'KZ',
    'Republic of Kazakhstan' : 	'KZ',
    'Cayman islands' : 	'KY',
    'Cambodia' : 	'KH',
    'Cameroon' : 	'CM',
    'Canada' : 	'CA',
    'Qatar' : 	'QA',
    'Kenya' : 	'KE',
    'Cyprus' : 	'CY',
    'Kyrgyzstan' : 	'KG',
    'Kyrgyz Republic' : 	'KG',
    'Kiribati' : 	'KI',
    'China' : 	'CN',
    'People\'s Republic of China' : 	'CN',
    'Korea (North)' : 	'KP',
    'Cocos (Keeling) islands' : 	'CC',
    'Colombia' : 	'CO',
    'Comoros' : 	'KM',
    'Korea' :   'KR',
    'South Korea':  'KR',
    'Korea (South)' :   'KR',
    'Republic of Korea':    'KR',
    'Korea (the Republic of)':    'KR',
    'Kosovo' : 	'XK',
    'Costa Rica' : 	'CR',
    'Cote D Ivoire' : 	'CI',
    'Cuba' : 	'CU',
    'Kuwait' : 	'KW',
    'Cook islands' : 	'CK',
    'Curacao' : 	'CW',
    'Laos' : 	'LA',
    'Latvia' : 	'LV',
    'Lesotho' : 	'LS',
    'Liberia' : 	'LR',
    'Lebanon' : 	'LB',
    'Libya' : 	'LY',
    'Lithuania' : 	'LT',
    'Liechtenstein' : 	'LI',
    'Luxembourg' : 	'LU',
    'Mauritius' : 	'MU',
    'Mauritania' : 	'MR',
    'Madagascar' : 	'MG',
    'Mayotte' : 	'YT',
    'Macao' : 	'MO',
    'Macau' : 	'MO',
    'Macedonia' : 	'MK',
    'North Macedonia' : 'MK',
    'FYR Macedonia' : 'MK',
    'Former Yugoslavian Republic of Macedonia' : 'MK',
    'Malawi' : 	'MW',
    'Malaysia' : 	'MY',
    'Mali' : 	'ML',
    'United States minor outlying islands' : 	'UM',
    'Maldives' : 	'MV',
    'Malta' : 	'MT',
    'Morocco' : 	'MA',
    'Martinique' : 	'MQ',
    'Marshall islands' : 	'MH',
    'Mexico' : 	'MX',
    'Micronesia (federated states of)' : 	'FM',
    'Mozambique' : 	'MZ',
    'Moldova (republic of)' : 	'MD',
    'Moldova' : 	'MD',
    'Republic of Moldova' : 	'MD',
    'Republic Of Moldova' : 	'MD',
    'Monaco' : 	'MC',
    'Mongolia' : 	'MN',
    'Montserrat' : 	'MS',
    'Myanmar' : 	'MM',
    'Isle of Man' : 	'IM',
    'Namibia' : 	'NA',
    'Nauru' : 	'NR',
    'Nepal' : 	'NP',
    'Niger' : 	'NE',
    'Nigeria' : 	'NG',
    'Netherlands' : 	'NL',
    'Nicaragua' : 	'NI',
    'Niue' : 	'NU',
    'New Zealand' : 	'NZ',
    'New Caledonia' : 	'NC',
    'Norway' : 	'NO',
    'Norfolk island' : 	'NF',
    'United Arab Emirates' : 	'AE',
    'Oman' : 	'OM',
    'Pakistan' : 	'PK',
    'Palau' : 	'PW',
    'Palestine' : 	'PS',
    'Panama' : 	'PA',
    'Papua New Guinea' : 	'PG',
    'Paraguay' : 	'PY',
    'Peru' : 	'PE',
    'Pitcairn' : 	'PN',
    'Poland' : 	'PL',
    'Portugal' : 	'PT',
    'Puerto Rico' : 	'PR',
    'Congo' : 	'CG',
    'R?union' : 	'RE',
    'Christmas island' : 	'CX',
    'Russia' : 	'RU',
    'Russian Federation' : 	'RU',
    'Rwanda' : 	'RW',
    'Romania' : 	'RO',
    'El Salvador' : 	'SV',
    'Salvador' : 	'SV',
    'Samoa' : 	'WS',
    'San Marino' : 	'SM',
    'Sao Tome and Principe' : 	'ST',
    'Saudi Arabia' : 	'SA',
    'Swaziland' : 	'SZ',
    'Saint Helena, Ascension, Tristan da Cunha' : 	'SH',
    'Northern Мariana islands' : 	'MP',
    'Seychelles' : 	'SC',
    'Saint Barthelemy' : 	'BL',
    'Senegal' : 	'SN',
    'Saint Мartin (french part)' : 	'MF',
    'Saint Pierre and Miquelon' : 	'PM',
    'Saint Vincent and the Grenadines' : 	'VC',
    'Saint Kitts and Nevis' : 	'KN',
    'Saint Lucia' : 	'LC',
    'Sint Maarten (dutch part)' : 	'SX',
    'Serbia' : 	'RS',
    'Singapore' : 	'SG',
    'Republic of Singapore' : 	'SG',
    'Syria' : 	'SY',
    'Syrian Arab Republic' : 	'SY',
    'Slovakia' : 	'SK',
    'Slovak Republic' : 	'SK',
    'Slovenia' : 	'SI',
    'United States of America' : 	'US',
    'United States' : 	'US',
    'Solomon islands' : 	'SB',
    'Somalia' : 	'SO',
    'Sudan' : 	'SD',
    'Suriname' : 	'SR',
    'Sierra Leone' : 	'SL',
    'Tajikistan' : 	'TJ',
    'Thailand' : 	'TH',
    'Taiwan' : 	'TW',
    'Chinese Taipei' : 	'TW',
    'Tanzania' : 	'TZ',
    'Turks and Caicos islands' : 	'TC',
    'Timor-Leste' : 	'TL',
    'Togo' : 	'TG',
    'Tokelau' : 	'TK',
    'Tonga' : 	'TO',
    'Trinidad and Tobago' : 	'TT',
    'Tuvalu' : 	'TV',
    'Tunisia' : 	'TN',
    'Turkmenistan' : 	'TM',
    'Turkey' : 	'TR',
    'Uganda' : 	'UG',
    'Uzbekistan' : 	'UZ',
    'Ukraine' : 	'UA',
    'Wallis and Futuna' : 	'WF',
    'Uruguay' : 	'UY',
    'Faroe islands' : 	'FO',
    'Fiji' : 	'FJ',
    'Philippines' : 	'PH',
    'Finland' : 	'FI',
    'Falkland islands (Malvinas)' : 	'FK',
    'France' : 	'FR',
    'French Guiana' : 	'GF',
    'French Polynesia' : 	'PF',
    'French southern territories' : 	'TF',
    'Heard island and McDonald islands' : 	'HM',
    'Croatia' : 	'HR',
    'Central African republic' : 	'CF',
    'Chad' : 	'TD',
    'Montenegro' : 	'ME',
    'Czechia' : 	'CZ',
    'Czech Republic' : 	'CZ',
    'Chile' : 	'CL',
    'Switzerland' : 	'CH',
    'Sweden' : 	'SE',
    'Svalbard and Jan Mayen' : 	'SJ',
    'Sri Lanka' : 	'LK',
    'Ecuador' : 	'EC',
    'Equatorial Guinea' : 	'GQ',
    'Aland islands' : 	'AX',
    'Eritrea' : 	'ER',
    'Estonia' : 	'EE',
    'Ethiopia' : 	'ET',
    'South Georgia and the South Sandwich islands' : 	'GS',
    'South Оssetia' : 	'OS',
    'South Africa' : 	'ZA',
    'South Sudan' : 	'SS',
    'Jamaica' : 	'JM',
    'Japan' : 	'JP',

    'Абхазия' : 	'AB',
    'Австралия' : 	'AU',
    'Австрия' : 	'AT',
    'Азербайджан' : 	'AZ',
    'Албания' : 	'AL',
    'Алжир' : 	'DZ',
    'Ангилья' : 	'AI',
    'Ангола' : 	'AO',
    'Андорра' : 	'AD',
    'Антарктика' : 	'AQ',
    'Антигуа и Барбуда' : 	'AG',
    'Аргентина' : 	'AR',
    'Армения' : 	'AM',
    'Аруба' : 	'AW',
    'Афганистан' : 	'AF',
    'Багамы' : 	'BS',
    'Бангладеш' : 	'BD',
    'Барбадос' : 	'BB',
    'Бахрейн' : 	'BH',
    'Беларусь' : 	'BY',
    'Республика Беларусь' : 	'BY',
    'Белиз' : 	'BZ',
    'Бельгия' : 	'BE',
    'Бенин' : 	'BJ',
    'Бермуды' : 	'BM',
    'Болгария' : 	'BG',
    'Боливия' : 	'BO',
    'Бонэйр, Синт-Эстатиус и Саба' : 	'BQ',
    'Босния и Герцеговина' : 	'BA',
    'Ботсвана' : 	'BW',
    'Бразилия' : 	'BR',
    'Британские Виргинские острова' : 	'VG',
    'Британские территории в Индийском океане' : 	'IO',
    'Бруней' : 	'BN',
    'Буве острова' : 	'BV',
    'Буркина-Фасо' : 	'BF',
    'Бурунди' : 	'BI',
    'Бутан' : 	'BT',
    'Вануату' : 	'VU',
    'Ватикан' : 	'VA',
    'Великобритания' : 	'GB',
    'Венгрия' : 	'HU',
    'Венесуэла' : 	'VE',
    'Виргинские острова (США)' : 	'VI',
    'Самоа Восточное' : 	'AS',
    'Вьетнам' : 	'VN',
    'Габон' : 	'GA',
    'Гаити' : 	'HT',
    'Гайана' : 	'GY',
    'Гамбия' : 	'GM',
    'Гана' : 	'GH',
    'Гваделупа' : 	'GP',
    'Гватемала' : 	'GT',
    'Гвинея' : 	'GN',
    'Гвинея-бисау' : 	'GW',
    'Германия' : 	'DE',
    'Гернси' : 	'GG',
    'Гибралтар' : 	'GI',
    'Гондурас' : 	'HN',
    'Гонконг' : 	'HK',
    'Гренада' : 	'GD',
    'Гренландия' : 	'GL',
    'Греция' : 	'GR',
    'Грузия' : 	'GE',
    'Гуам' : 	'GU',
    'Дания' : 	'DK',
    'Конго (ДР)' : 	'CD',
    'Джерси' : 	'JE',
    'Джибути' : 	'DJ',
    'Доминика' : 	'DM',
    'Доминиканская республика' : 	'DO',
    'Египет' : 	'EG',
    'Замбия' : 	'ZM',
    'Западная Сахара' : 	'EH',
    'Зимбабве' : 	'ZW',
    'Израиль' : 	'IL',
    'Индия' : 	'IN',
    'Индонезия' : 	'ID',
    'Иордания' : 	'JO',
    'Ирак' : 	'IQ',
    'Иран' : 	'IR',
    'Ирландия' : 	'IE',
    'Исландия' : 	'IS',
    'Испания' : 	'ES',
    'Италия' : 	'IT',
    'Йемен' : 	'YE',
    'Кабо-верде' : 	'CV',
    'Казахстан' : 	'KZ',
    'Республика Казахстан' : 	'KZ',
    'Каймановы острова' : 	'KY',
    'Камбоджа' : 	'KH',
    'Камерун' : 	'CM',
    'Канада' : 	'CA',
    'Катар' : 	'QA',
    'Кения' : 	'KE',
    'Кипр' : 	'CY',
    'Киргизия' : 	'KG',
    'Кыргызстан' : 	'KG',
    'Кыргызская Республика' : 	'KG',
    'Кирибати' : 	'KI',
    'Китай' : 	'CN',
    'КНДР' : 	'KP',
    'Кокосовые острова' : 	'CC',
    'Колумбия' : 	'CO',
    'Коморы' : 	'KM',
    'Корея Южная' : 	'KR',
    'Косово' : 	'XK',
    'Коста-Рика' : 	'CR',
    'Кот Д Ивуар' : 	'CI',
    'Куба' : 	'CU',
    'Кувейт' : 	'KW',
    'Кука острова' : 	'CK',
    'Кюрасао' : 	'CW',
    'Лаос' : 	'LA',
    'Латвия' : 	'LV',
    'Лесото' : 	'LS',
    'Либерия' : 	'LR',
    'Ливан' : 	'LB',
    'Ливия' : 	'LY',
    'Литва' : 	'LT',
    'Лихтенштейн' : 	'LI',
    'Люксембург' : 	'LU',
    'Маврикий' : 	'MU',
    'Мавритания' : 	'MR',
    'Мадагаскар' : 	'MG',
    'Майотта' : 	'YT',
    'Макао' : 	'MO',
    'Македония' : 	'MK',
    'Малави' : 	'MW',
    'Малайзия' : 	'MY',
    'Мали' : 	'ML',
    'Малые тихоокеанские острова Соединенных Штатов' : 	'UM',
    'Мальдивы' : 	'MV',
    'Мальта' : 	'MT',
    'Марокко' : 	'MA',
    'Мартиника' : 	'MQ',
    'Маршалловы острова' : 	'MH',
    'Мексика' : 	'MX',
    'Микронезия' : 	'FM',
    'Мозамбик' : 	'MZ',
    'Молдова' : 	'MD',
    'Республика Молдова' : 	'MD',
    'Монако' : 	'MC',
    'Монголия' : 	'MN',
    'Монтсеррат' : 	'MS',
    'Мьянма' : 	'MM',
    'Мэн остров' : 	'IM',
    'Намибия' : 	'NA',
    'Науру' : 	'NR',
    'Непал' : 	'NP',
    'Нигер' : 	'NE',
    'Нигерия' : 	'NG',
    'Нидерланды' : 	'NL',
    'Никарагуа' : 	'NI',
    'Ниуэ' : 	'NU',
    'Новая Зеландия' : 	'NZ',
    'Новая Каледония' : 	'NC',
    'Норвегия' : 	'NO',
    'Норфолк остров' : 	'NF',
    'Объединенные Арабские эмираты' : 	'AE',
    'Оман' : 	'OM',
    'Пакистан' : 	'PK',
    'Палау' : 	'PW',
    'Палестина' : 	'PS',
    'Панама' : 	'PA',
    'Папуа Новая Гвинея' : 	'PG',
    'Парагвай' : 	'PY',
    'Перу' : 	'PE',
    'Питкерн' : 	'PN',
    'Польша' : 	'PL',
    'Португалия' : 	'PT',
    'Пуэрто-Рико' : 	'PR',
    'Конго Республика' : 	'CG',
    'Реюньон' : 	'RE',
    'Рождества остров' : 	'CX',
    'Россия' : 	'RU',
    'Российская Федерация' : 	'RU',
    'Руанда' : 	'RW',
    'Румыния' : 	'RO',
    'Сальвадор' : 	'SV',
    'Самоа' : 	'WS',
    'Сан-Марино' : 	'SM',
    'Сан-Томе и Принсипи' : 	'ST',
    'Саудовская Аравия' : 	'SA',
    'Свазиленд' : 	'SZ',
    'Святая Eлена, о.Вознесения, Тристан-да-Кунья' : 	'SH',
    'Марианские острова (Северные)' : 	'MP',
    'Сейшелы' : 	'SC',
    'Сен-Бартелеми' : 	'BL',
    'Сенегал' : 	'SN',
    'Сен-Мартен (французская часть)' : 	'MF',
    'Сен-Пьер и Микелон' : 	'PM',
    'Сент-Винсент и Гренадины' : 	'VC',
    'Сент-Киттс и Невис' : 	'KN',
    'Сент-Люсия' : 	'LC',
    'Сент-Мартен (нидерландская часть)' : 	'SX',
    'Сербия' : 	'RS',
    'Сингапур' : 	'SG',
    'Сирия' : 	'SY',
    'Словакия' : 	'SK',
    'Словения' : 	'SI',
    'США' : 	'US',
    'Соломоновы острова' : 	'SB',
    'Сомали' : 	'SO',
    'Судан' : 	'SD',
    'Суринам' : 	'SR',
    'Сьерра-Леоне' : 	'SL',
    'Таджикистан' : 	'TJ',
    'Таиланд' : 	'TH',
    'Тайвань' : 	'TW',
    'Танзания' : 	'TZ',
    'Теркс и Кайкос острова' : 	'TC',
    'Тимор-Лесте' : 	'TL',
    'Того' : 	'TG',
    'Токелау' : 	'TK',
    'Тонга' : 	'TO',
    'Тринидад и Тобаго' : 	'TT',
    'Тувалу' : 	'TV',
    'Тунис' : 	'TN',
    'Туркмения' : 	'TM',
    'Туркменистан' : 	'TM',
    'Турция' : 	'TR',
    'Уганда' : 	'UG',
    'Узбекистан' : 	'UZ',
    'Украина' : 	'UA',
    'Уоллeс и Футуна острова' : 	'WF',
    'Уругвай' : 	'UY',
    'Фарерские острова' : 	'FO',
    'Фиджи' : 	'FJ',
    'Филиппины' : 	'PH',
    'Финляндия' : 	'FI',
    'Фолклендские (Мальвинские) острова' : 	'FK',
    'Франция' : 	'FR',
    'Французская Гвиана' : 	'GF',
    'Французская Полинезия' : 	'PF',
    'Французские южные территории' : 	'TF',
    'Херд и Макдональд острова' : 	'HM',
    'Хорватия' : 	'HR',
    'Центрально-Африканская республика' : 	'CF',
    'Чад' : 	'TD',
    'Черногория' : 	'ME',
    'Чехия' : 	'CZ',
    'Чили' : 	'CL',
    'Швейцария' : 	'CH',
    'Швеция' : 	'SE',
    'Шпицберген и Ян-Майен' : 	'SJ',
    'Шри Ланка' : 	'LK',
    'Эквадор' : 	'EC',
    'Экваториальная Гвинея' : 	'GQ',
    'Аландские острова' : 	'AX',
    'Эритрея' : 	'ER',
    'Эстония' : 	'EE',
    'Эфиопия' : 	'ET',
    'Южная Джорджия и Южные Сандвичевы острова' : 	'GS',
    'Южная Осетия' : 	'OS',
    'Южно-Африканская Республика' : 	'ZA',
    'Южный Судан' : 	'SS',
    'Ямайка' : 	'JM',
    'Япония' : 	'JP',
}

# print(countryToCode['Kazakhstan'])
